server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:postgresql://localhost/cambio_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
  flyway:
    locations:
    - classpath:/db_migration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
